# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_BllA2xwqh231oErdqczCOi_fo8xPwrP
"""

!pip install pyngrok flask opencv-python-headless segment_anything numpy torch torchvision
!wget https://dl.fbaipublicfiles.com/segment_anything/sam_vit_b_01ec64.pth

import os
import torch
import cv2
import numpy as np
import base64
import requests
from flask import Flask, request, jsonify
from pyngrok import ngrok
from segment_anything import sam_model_registry, SamPredictor
from torchvision import models, transforms
from PIL import Image

app = Flask(__name__)

# --- 1. NGROK & BAĞLANTI ---
ngrok.set_auth_token("3BTLNcg2YKDVNyTL4QjPP0uO3XR_GQbLoteTk6GHZjJSeUWb")
public_url = ngrok.connect(5000).public_url
print(f"\n---> API Adresiniz: {public_url}/process <---\n")

# --- 2. MODELLERİN YÜKLENMESİ (SAM + MOBILENET) ---
device = "cuda" if torch.cuda.is_available() else "cpu"
print(f"Modeller {device} üzerinde yükleniyor...")

# SAM Modeli (Çıkartma Kesimi İçin)
sam_checkpoint = "sam_vit_b_01ec64.pth"
model_type = "vit_b"
sam = sam_model_registry[model_type](checkpoint=sam_checkpoint)
sam.to(device=device)
predictor = SamPredictor(sam)

# MobileNetV2 (Nesne Doğrulama İçin)
classifier = models.mobilenet_v2(pretrained=True).to(device).eval()
labels_url = "https://raw.githubusercontent.com/pytorch/hub/master/imagenet_classes.txt"
imagenet_labels = requests.get(labels_url).text.splitlines()

print("Sistem Hazır!")

# --- 3. YARDIMCI FONKSİYONLAR ---

def clean_mask(mask):
    """Çıkartma kenarlarını pürüzsüzleştiren o 'süper' fonksiyon."""
    mask_uint8 = (mask * 255).astype(np.uint8)
    contours, _ = cv2.findContours(mask_uint8, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)
    if not contours: return mask_uint8
    c = max(contours, key=cv2.contourArea)
    new_mask = np.zeros_like(mask_uint8)
    cv2.drawContours(new_mask, [c], -1, 255, thickness=cv2.FILLED)
    new_mask = cv2.GaussianBlur(new_mask, (5, 5), 0)
    _, new_mask = cv2.threshold(new_mask, 127, 255, cv2.THRESH_BINARY)
    return new_mask

def validate_object(image_rgb, target_name):
    """Yapay Zeka ile nesne kontrolü yapan yeni katman."""
    preprocess = transforms.Compose([
        transforms.Resize(256),
        transforms.CenterCrop(224),
        transforms.ToTensor(),
        transforms.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225]),
    ])

    img_pil = Image.fromarray(image_rgb)
    img_t = preprocess(img_pil).unsqueeze(0).to(device)

    with torch.no_grad():
        output = classifier(img_t)

    _, indices = torch.sort(output, descending=True)
    # İlk 10 tahmini kontrol et (Daha esnek olması için)
    top10_predictions = [imagenet_labels[idx].lower() for idx in indices[0][:10]]

    target = target_name.lower()
    # Tahminlerin içinde hedef kelime geçiyor mu?
    is_correct = any(target in p or p in target for p in top10_predictions)

    return is_correct, top10_predictions[0]

# --- 4. ANA İŞLEM (PROCESS) ---

@app.route('/process', methods=['POST'])
def process_image():
    try:
        file = request.files['image']
        target_name = request.form.get('target_object', 'object')

        file_bytes = np.frombuffer(file.read(), np.uint8)
        image = cv2.imdecode(file_bytes, cv2.IMREAD_COLOR)
        image_rgb = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)

        # A. ÇIKARTMA YAPMA (SAM MANTIĞI)
        h, w = image_rgb.shape[:2]
        box_w, box_h = w * 0.4, h * 0.4
        x_min, y_min = int((w - box_w) / 2), int((h - box_h) / 2)
        x_max, y_max = int((w + box_w) / 2), int((h + box_h) / 2)
        input_box = np.array([x_min, y_min, x_max, y_max])

        predictor.set_image(image_rgb)
        masks, scores, _ = predictor.predict(box=input_box, multimask_output=True)
        best_mask = masks[np.argmax(scores)]

        cleaned_mask_255 = clean_mask(best_mask)
        final_mask_bool = cleaned_mask_255 > 0

        coords = np.column_stack(np.where(final_mask_bool))
        if coords.size == 0:
            return jsonify({'status': 'error', 'message': 'Nesne algılanamadı'})

        y_min_c, x_min_c = coords.min(axis=0)
        y_max_c, x_max_c = coords.max(axis=0)

        transparent_image = np.zeros((h, w, 4), dtype=np.uint8)
        transparent_image[:, :, :3] = image
        transparent_image[:, :, 3] = cleaned_mask_255

        cropped_sticker = transparent_image[y_min_c:y_max_c+1, x_min_c:x_max_c+1]

        # Boyutlandırma ve Base64
        max_dim = 800
        ch, cw = cropped_sticker.shape[:2]
        scale = max_dim / max(ch, cw)
        if scale < 1:
            cropped_sticker = cv2.resize(cropped_sticker, (int(cw * scale), int(ch * scale)))

        _, buffer = cv2.imencode('.png', cropped_sticker)
        encoded_image = base64.b64encode(buffer).decode('utf-8')

        # B. DOĞRULAMA (YENİ MANTIK)
        # Orijinal resim üzerinden AI'ya ne olduğunu soruyoruz
        is_correct, detected_name = validate_object(image_rgb, target_name)

        return jsonify({
            'status': 'success',
            'image': encoded_image,
            'is_correct': is_correct,
            # 'detected_object' alanını silebiliriz veya boş gönderebiliriz
            'message': 'Çıkartma oluşturuldu!'
        })

    except Exception as e:
        return jsonify({'status': 'error', 'message': str(e)})

if __name__ == '__main__':
    app.run(port=5000)